//everything in here is only for my personal reference, no code no variables nothing here

//engine macros
// ENGINE_MACROS_HEADER

//Engine
// ENGINE_HEADER

//Scene
// SCENE_HEADER

//Renderer
// RENDERER_HEADER

//Event Handler
// OBSERVER_HEADER
// SUBJECT_HEADER

//Input Handling
// COMMAND_BASE_HEADER
// COMMANDSET_PLAYER_HEADER
// XINPUT_CONTROL_INFORMATION_HEADER
// KEYBOARD_CONTROL_INFORMATION_HEADER
// INPUT_HANDLER_HEADER



//Game Resources

// RESOURCE_OWNER_HEADER
// FONT_HEADER
// TEXTURE2D_HEADER
// SPRITESHEET_HEADER



//GameObject
// GAMEOBJECT_HEADER


//Gameobject Components
// GAMEOBJECT_COMPONENT_BASE_HEADER

// COMPONENT_TEXTURE2D_HEADER
// COMPONENT_TRANSFORM_HEADER
// COMPONENT_LOCOMOTION_HEADER
// COMPONENT_HEALTH_HEADER
// COMPONENT_SCORETRACKER_HEADER

// COMPONENT_TEXT_HEADER
// COMPONENT_ORBIT_HEADER
// COMPONENT_RENDER_HEADER
// COMPONENT_FPS_HEADER
// COMPONENT_ANIMATED_TEXTURE2D_COMPONENT_HEADER
//COMPONENT_UI_TEXT_HEADER

// COMPONENT_CACHE_TRASHER_HEADER

